version: "3"
services:
  spotdl:
    image: "spotdl/spotify-downloader"
    command: web --host 0.0.0.0 --port 8800 --client-id ${SPOTIFY_CLIENT_ID} --client-secret ${SPOTIFY_CLIENT_SECRET}
    ports:
      - "8000:8800"
    volumes:
      - .:/music
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
